# Generated by Django 5.0 on 2024-02-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password_reset',
        ),
    ]
