# Generated by Django 5.0 on 2024-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='systemsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automate', models.BooleanField(default=False)),
                ('enforce_blacklist', models.BooleanField(default=False)),
                ('backlist_add', models.BooleanField(default=True)),
                ('report_add', models.BooleanField(default=True)),
            ],
        ),
    ]
