# Generated by Django 5.0 on 2024-02-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='staffidi',
            new_name='staffid',
        ),
    ]
