# Generated by Django 5.0 on 2024-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_staffidi_alert_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
