# Generated by Django 5.0 on 2024-02-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_systemsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='backlist_add',
            new_name='blacklist_add',
        ),
    ]
