# Generated by Django 5.0 on 2024-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_backlist_add_systemsettings_blacklist_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='settings_class',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
