# Generated by Django 5.0 on 2024-02-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_report_reportid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='blacklistid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
