# Generated by Django 5.0 on 2024-02-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_systemsettings_settings_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='settings_class',
            field=models.CharField(default='general', max_length=20, primary_key=True, serialize=False),
        ),
    ]
