# Generated by Django 5.0 on 2024-02-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_blacklist_blacklistid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='verification',
            field=models.CharField(default='waiting', max_length=30),
        ),
    ]
