# Generated by Django 5.0 on 2024-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_report_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='verification',
            field=models.CharField(max_length=30),
        ),
    ]
