# Generated by Django 5.0 on 2024-02-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_systemsettings_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='location',
            new_name='locations',
        ),
    ]
