# Generated by Django 5.0 on 2024-02-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_systemsettings_automate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='locations',
            field=models.CharField(choices=[('none', 'none'), ('Kiambu01', 'Kiambu01'), ('Kiambu0', 'Kiambu02'), ('Thika01', 'Thika01'), ('Thika02', 'Thika02'), ('Online', 'Online')], default='all', max_length=50),
        ),
    ]
