# Generated by Django 5.0 on 2024-02-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_alert_timestamp_report_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='stations',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='automate',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='blacklist_add',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='locations',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='report_add',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
