# Generated by Django 5.0 on 2024-03-04 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_systemsettings_stations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 21, 48, 49, 249942, tzinfo=datetime.timezone.utc)),
        ),
    ]
